# Generated by Django 6.0.2 on 2026-03-08 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Property name (e.g., 'Sunset Apartments')", max_length=200)),
                ('address', models.CharField(help_text='Full street address', max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Property description and amenities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'LANDLORD'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text="Unit identifier (e.g., '204', 'A-12', 'Ground Floor')", max_length=50)),
                ('floor', models.IntegerField(blank=True, help_text='Floor number (0=Ground, 1=First, etc.)', null=True)),
                ('bedrooms', models.PositiveIntegerField(default=1, help_text='Number of bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, help_text='Number of bathrooms (e.g., 1.5, 2.0)', max_digits=3)),
                ('square_feet', models.PositiveIntegerField(blank=True, help_text='Unit size in square feet', null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Monthly rent amount', max_digits=10)),
                ('is_occupied', models.BooleanField(default=False, help_text='Is unit currently occupied?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['property', 'unit_number'],
                'unique_together': {('property', 'unit_number')},
            },
        ),
    ]
