# Generated by Django 6.0.2 on 2026-03-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Property photo', null=True, upload_to='property_images/%Y/%m/%d'),
        ),
    ]
