# Generated by Django 6.0.2 on 2026-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo video URL (e.g., https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
