# Generated by Django 6.0.2 on 2026-03-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Property photo', upload_to='property_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text="Image caption or description (e.g., 'Main Entrance', 'Swimming Pool')", max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Unit photo', upload_to='unit_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text="Image caption (e.g., 'Living Room', 'Master Bedroom')", max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(help_text='Unit this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Unit Image',
                'verbose_name_plural': 'Unit Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
