# Generated by Django 6.0.2 on 2026-03-08 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Full name of emergency contact', max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=20, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text="Relationship to tenant (e.g., 'Mother', 'Brother')", max_length=100, null=True)),
                ('id_document', models.FileField(blank=True, help_text="ID card, passport, or driver's license", null=True, upload_to='tenant_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Profile',
                'verbose_name_plural': 'Tenant Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
