"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config #tool that reads .env files

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    #my apps
    'apps.users',
    'apps.properties',
    'apps.leases',
    'apps.payments',
    'apps.maintenance',

    #third-party apps
    'django_ratelimit',
    'django.contrib.humanize',


    #default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

#===========================================================================
# PASSWORD VALIDATION (Phase 17)
# ============================================================================
# Enforces strong password requirements for all new passwords.
# Applied during: registration, pass=word change, password reset
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        # Rejects passwords too similar to username/email
        # Example: username "marshdev" → rejects "marshdev123"
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Minimum 8 characters required
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        # Blocks 20,000 common passwords (built into Django)
        # Rejects: "password", "admin123", "qwerty", etc.
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Rejects all-numeric passwords
        # Blocks: "12345678", "19920415"
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# CUSTOM USER MODEL
# ============================================================================

AUTH_USER_MODEL = 'users.User'
# Tell Django to use our custom User model instead of the default one
# Format: 'app_name.ModelName'
# This MUST be set before migrations

# ============================================================================
# AUTHENTICATION SETTINGS
# ============================================================================
LOGIN_URL = 'login'  # URL name for login view
LOGIN_REDIRECT_URL = 'home'  # URL name to redirect after login

# Message tags for Bootstrap compatibility
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# Custom error handlers
HANDLER404 = 'django.views.defaults.page_not_found'
HANDLER403 = 'django.views.defaults.permission_denied'
HANDLER500 = 'django.views.defaults.server_error'

# ============================================================================
# SESSION SECURITY (Phase 17)
# ============================================================================
# Controls session lifetime and cookie protection
# ============================================================================

# Session expires after 30 minutes of inactivity
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds

# Session ends when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# JavaScript cannot access session cookie (XSS protection)
SESSION_COOKIE_HTTPONLY = True

# CSRF protection for cookies
SESSION_COOKIE_SAMESITE = 'Lax'

# ============================================================================
# SECURITY HEADERS (Phase 17)
# ============================================================================
# HTTP headers that protect against common attacks
# ============================================================================

# Prevents browsers from MIME-sniffing content types
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enables browser's XSS filter (older browsers)
SECURE_BROWSER_XSS_FILTER = True

# Prevents site from being embedded in iframes (clickjacking protection)
X_FRAME_OPTIONS = 'DENY'

